### ISSUE TITLE
Reconsider using `sudo` as name for the project to prevent confusion

### ISSUE THREAD

**Issue by j0057** [microsoft/sudo#81] opened 2024-05-24 20:39 UTC
Current names for similar functionality include `su`, `sudo`, `sudo-rs`, `doas`, `runas`, `run0`, `ssu`, `pkexec`.

Also see https://github.com/PowerShell/PowerShell/pull/1901.

**Comment by a1batross** [comment] 2024-05-27 15:21
Embrace
Extend <= we are here
Extinguish

**Comment by zadjii-msft** [comment] 2024-05-27 20:39
This is discussed more in #23 and answered in https://github.com/microsoft/sudo/discussions/23#discussioncomment-8422957. 

/duplicate of #23

Thanks!

**Closed by zadjii-msft** 2024-05-27 20:39 UTC
Labels: Resolution-Duplicate
